apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-deployment
  labels:
    app: blue-green-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-green-deployment
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blue-green-deployment
    spec:
      containers:
      - name: udacity-capstone
        image: mimiobi/udacity-capstone:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: blue-green-deployment
spec:
  selector:
    app: blue-green-deployment
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer
---
